plugin:
   prefix: '&a[CustomMOTD] &r'
   update-check: true
   ##If set to false you will not longer get the messages "no update available" if you join the server
   no-update-available-message-on-join: false
servers:
   ##You can add or remove servers, name doesn't matter
   ##Don't modify the name "default"!
   ##If the serverlist can't find the server (it's not defined here) it will show the default motd!
   default:
      motd:
         enabled: true
         line1: '&aThe coolest server in the universe!'
         line2: '&aPlugin made by tvhee!'
         center: false
      favicon:
         enabled: true
         file: default.png
      hover:
         enabled: true
         text:
            - '&6Welcome on this server!'
            - '&aPlugin made by tvhee'
         center: false
   server2:
      motd:
         enabled: true
         line1: '&aThe coolest server in the universe!'
         line2: '&aPlugin made by tvhee!'
         center: false
      favicon:
         enabled: true
         file: default.png
      hover:
         enabled: true
         text:
            - '&6Welcome on this server!'
            - '&aPlugin made by tvhee'
         center: false
      ##Use the external ip's which everybody could reach (not localhost)
      ip: ip2.test.net
   server3:
      motd:
         enabled: true
         line1: '&aThe coolest server in the universe!'
         line2: '&aPlugin made by tvhee!'
         center: false
      favicon:
         enabled: true
         file: default.png
      hover:
         enabled: true
         text:
            - '&6Welcome on this server!'
            - '&aPlugin made by tvhee'
         center: false
      ##Use the external ip's which everybody could reach (not localhost)
      ip: ip2.test.net